//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 
using MessageValidator.Definition;


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class MessageDefinition {
    
    private MessageItemDefinition[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Group", typeof(GroupDefinition))]
    [System.Xml.Serialization.XmlElementAttribute("Segment", typeof(SegmentDefinition))]
    public MessageItemDefinition[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GroupDefinition : MessageItemDefinition {
    
    private MessageItemDefinition[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Group", typeof(GroupDefinition))]
    [System.Xml.Serialization.XmlElementAttribute("Segment", typeof(SegmentDefinition))]
    public MessageItemDefinition[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class SegmentDefinition : MessageItemDefinition {
    
    private FieldDefinition[] fieldField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Field")]
    public FieldDefinition[] Field {
        get {
            return this.fieldField;
        }
        set {
            this.fieldField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class FieldDefinition : ICommonDefinition{
    
    private ComponentDefinition[] componentField;
    
    private string nameField;
    
    private string repeatField;
    
    private string optionalField;
    
    private DataTypes dataTypeField;
    
    private bool dataTypeFieldSpecified;
    
    private int lengthField;
    
    private int sequenceField;
    
    private string tableNumberField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Component")]
    public ComponentDefinition[] Component {
        get {
            return this.componentField;
        }
        set {
            this.componentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string repeat {
        get {
            return this.repeatField;
        }
        set {
            this.repeatField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string optional {
        get {
            return this.optionalField;
        }
        set {
            this.optionalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public DataTypes dataType {
        get {
            return this.dataTypeField;
        }
        set {
            this.dataTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool dataTypeSpecified {
        get {
            return this.dataTypeFieldSpecified;
        }
        set {
            this.dataTypeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int length {
        get {
            return this.lengthField;
        }
        set {
            this.lengthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int sequence {
        get {
            return this.sequenceField;
        }
        set {
            this.sequenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string tableNumber {
        get {
            return this.tableNumberField;
        }
        set {
            this.tableNumberField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ComponentDefinition : ICommonDefinition {
    
    private ComponentDefinition[] componentField;
    
    private string nameField;
    
    private int sequenceField;
    
    private int lengthField;
    
    private DataTypes dataTypeField;
    
    private bool dataTypeFieldSpecified;
    
    private string optionalField;
    
    private string tableNumberField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Component")]
    public ComponentDefinition[] Component {
        get {
            return this.componentField;
        }
        set {
            this.componentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int sequence {
        get {
            return this.sequenceField;
        }
        set {
            this.sequenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int length {
        get {
            return this.lengthField;
        }
        set {
            this.lengthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public DataTypes dataType {
        get {
            return this.dataTypeField;
        }
        set {
            this.dataTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool dataTypeSpecified {
        get {
            return this.dataTypeFieldSpecified;
        }
        set {
            this.dataTypeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string optional {
        get {
            return this.optionalField;
        }
        set {
            this.optionalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string tableNumber {
        get {
            return this.tableNumberField;
        }
        set {
            this.tableNumberField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
public enum DataTypes {
    
    /// <remarks/>
    DT,
    
    /// <remarks/>
    DTM,
    
    /// <remarks/>
    FT,
    
    /// <remarks/>
    ID,
    
    /// <remarks/>
    IS,
    
    /// <remarks/>
    NM,
    
    /// <remarks/>
    SI,
    
    /// <remarks/>
    ST,
    
    /// <remarks/>
    TN,
    
    /// <remarks/>
    TS,
    
    /// <remarks/>
    TX,
    
    /// <remarks/>
    VARIES,
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(SegmentDefinition))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(GroupDefinition))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public abstract partial class MessageItemDefinition {
    
    private string optionalField;
    
    private string repeatField;
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string optional {
        get {
            return this.optionalField;
        }
        set {
            this.optionalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string repeat {
        get {
            return this.repeatField;
        }
        set {
            this.repeatField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}
